openseamap add csv and markers, haversine_distance fix
kirienko/gpx-player pull request #5
Opened 2024-11-19 23:42 UTC by AAsyunkin-se

Hiya, some amendments for you, not sure if you need them? :)

- haversine_distance in main.py not using gpxpy
openseamap.py:
- added basic CSV import instead of GPX
- added --marks support
- marks file can now have an optional mark name

Cheers

2025-02-15 15:42 UTC, kirienko requested changes
Hi, first of all, thank you for your contribution! I'm always happy to see that someone uses my code.

Secondly, in your PR you try to solve three different problems:
 1. code clean up (`haversine_distance` removal)
 2. add `--marks` support
 3. add SCV support
But I would prefer to have separate pull requests per problem. 

I support the idea of removing `haversine_distance`; I wanted to do it myself but probably overlooked that. The same is true for `--marks` – I postponed it until the moment I needed it.

But I don't like the idea of CSV support. This software is named `gpx-player`, not `csv-player`. These are two very different formats: GPX is a well-defined XML, while CSV is a broad idea of column representation of data. I don't see a universal use case for CSV in the context of this software. But of course, no one can restrict you from supporting it in your own branch 😉

2025-02-16 11:37 UTC, AAsyunkin-se commented
Hi, I thought you didn't need anything at all,looking how there was no feedback in 3 months :)
As for CSV: Vakaros Atlas sailing comp uses CSV, hence the support.
And I made a mistake writing 'instead of GPX' as obviously GPX is supported all the same as it was. CSV is very useful if format is defined within the app/help.

2025-02-20 18:04 UTC, kirienko commented
Okay, if you have a device, it makes sense that you want to make it compatible with `gpx-player`. However, from a product perspective, the best approach would be to implement a separate module that converts the vendor-specific CSV into a proper GPX. This will not only allow you to use `gpx-player`, but also enable the whole variety of existing GPX software, like [gpx studio](https://gpx.studio/) for example.

I'm happy to add such a converter to the package if you want.

And it will make the maintenance of the system much easier.

2025-02-21 10:59 UTC, AAsyunkin-se commented
No problem at all, just let me know if you need any help from me and yes, Atlas support would be great!
As I said, I don't insist on merging my changes, you can do whatever you want with them :)

2025-07-20 15:30 UTC, closed without merging

2025-07-20 15:30 UTC, kirienko commented
This branch is closed as obsolete. But I will be happy to review the code with the changes addressed.